language: node_js
node_js:
  - stable
cache:
  directories:
    - "node_modules"
install:
  - npm ci
script:
  - npm run test
  - npm run build
  - npm run build:prod
  - npm run lint:ci
  - npm run lint-styles
